on:
  push:
    branches:
      - 'main'
    paths:
      - 'services/service-3/**.js'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: npm test
      - name: Build
        run: npm run build
      - name: run
        run: npm run start
