on:
  push:
    branches:
      - 'main'
    paths:
      - 'services/service-2/**.js'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: npm test --workspace=services/service-2
      - name: Build
        run: npm run build --workspace=services/service-2
      - name: run
        run: npm run start --workspace=services/service-2
